name: documentation_deploy

# https://github.com/YannickJadoul/Parselmouth/blob/master/.github/workflows/wheels.yml
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: true
        default: '3.10'

jobs:
  deploy_badge:
    runs-on: ubuntu-latest
    steps:
      - uses: MartinPdeS/MPSActions/install_package_on_manylinux@master
        with:
          python_version: ${{ inputs.python_version }}
          package_name: PyMieSim

      - uses: MartinPdeS/MPSActions/publish_documentation@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}