name: badge_deploy

# https://github.com/YannickJadoul/Parselmouth/blob/master/.github/workflows/wheels.yml
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: true
        default: '3.10'

jobs:
  deploy_badge:
    name: "Badge deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Set-up: Python ${{ inputs.python_version }}"
        uses: actions/setup-python@v4
        with:
          python-version: "${{ inputs.python_version }}"

      - name: "translate python version to cp"
        run: |
          TEMP=${{ matrix.python_version }}
          PYTHON_CP_VERSION="cp${TEMP//./}"
          echo "PYTHON_CP_VERSION=$PYTHON_CP_VERSION" >> $GITHUB_ENV

      - name: "Install: Dependencies for headless server"
        run: |
          sudo apt-get update
          sudo apt-get install libgl1-mesa-glx xvfb

      - name: "Download: wheel"
        uses: actions/download-artifact@v3
        with:
          path: ./dist

      - name: "Install pacakge"
        run: |
          python -m pip install --find-links ./dist/manylinux_wheel_pythoncp310 PyMieSim

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: "Install dev requirements"
        run: |
          python -m pip install -r requirements-dev.txt

      - name: "Computing total coverage"
        run: |
          cd tests
          coverage run -p -m pytest -s .
          coverage combine
          coverage report -m --skip-covered
          coverage json -o ./CoverageReport.json
          export TOTAL=$(python -c "import json; print(json.load(open('CoverageReport.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV

      - name: "Upload: Coverage badge"
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.MPdS_gist_token }}
          gistID: 2cac8ebb51cd9ce07dc7a955648301d5
          filename: PyMieSim_coverage_badge.json
          label: Coverage
          message: ${{ env.total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.total }}